export const CLOSE_TIP_MODAL = 'CLOSE_TIP_MODAL';
export const OPEN_TIP_MODAL = 'OPEN_TIP_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';
export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const OPEN_NETWORK_ERROR = 'OPEN_NETWORK_ERROR';
export const CLOSE_NETWORK_ERROR = 'CLOSE_NETWORK_ERROR';
