export const REQUEST_QUIZ_DATA = 'REQUEST_QUIZ_DATA';
export const RECEIVE_QUIZ_DATA = 'RECEIVE_QUIZ_DATA';
export const REQUEST_STATS_QUIZ_DATA = 'REQUEST_STATS_QUIZ_DATA';
export const RECEIVE_STATS_QUIZ_DATA = 'RECEIVE_STATS_QUIZ_DATA';
export const SAVE_QUESTION1_SELECT_ANSWER = 'SAVE_QUESTION1_SELECT_ANSWER';
export const SAVE_QUESTION1_FEEDBACK_SELECT_ANSWER =
    'SAVE_QUESTION1_FEEDBACK_SELECT_ANSWER';
export const SAVE_QUESTION3_SELECT_ANSWER = 'SAVE_QUESTION3_SELECT_ANSWER';
export const SAVE_QUESTION3_TEXT_ANSWER = 'SAVE_QUESTION3_TEXT_ANSWER';
export const SAVE_QUESTION3_FEEDBACK_TEXT_ANSWER =
    'SAVE_QUESTION3_FEEDBACK_TEXT_ANSWER';
export const SAVE_QUESTION3_FEEDBACK_SELECT_ANSWER =
    'SAVE_QUESTION3_FEEDBACK_SELECT_ANSWER';
export const SAVE_QUESTIONS = 'SAVE_QUESTIONS';
export const SAVE_USER = 'SAVE_USER';
export const UPDATE_OPERATION = 'UPDATE_OPERATION';
export const UPLOADING_QUESTIONS = 'UPLOADING_QUESTIONS';
export const UPLOADED_QUESTIONS = 'UPLOADED_QUESTIONS';
export const CLOSE_TIP_MODAL = 'CLOSE_TIP_MODAL';
export const OPEN_TIP_MODAL = 'OPEN_TIP_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';
export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const REQUEST_STATS_QUIZ_LIST = 'REQUEST_STATS_QUIZ_LIST';
export const RECEIVE_STATS_QUIZ_LIST = 'RECEIVE_STATS_QUIZ_LIST';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const NETWORK_ERROR_TIMEOUT = 'NETWORK_ERROR_TIMEOUT';
export const RESTORE_LOCAL_ANSWERS = 'RESTORE_LOCAL_ANSWERS';
export const RECORD_TIME = 'RECORD_TIME';
