export const CLOSE_ALERT = 'CLOSE_ALERT';
export const OPEN_ALERT = 'OPEN_ALERT';
export const CLOSE_CONFIRM = 'CLOSE_CONFIRM';
export const OPEN_CONFIRM = 'OPEN_CONFIRM';
export const OPEN_NETWORK_ERROR = 'OPEN_NETWORK_ERROR';
export const CLOSE_NETWORK_ERROR = 'CLOSE_NETWORK_ERROR';
