/**
 * Created by joe on 4/19/18.
 */
export const ACTION_LV = {
    REQUEST: 'LV_REQUEST',
    RECEIVE: 'LV_RECEIVE',
};

export const ACTION_LH = {
    REQUEST: 'LH_REQUEST',
    RECEIVE: 'LH_RECEIVE',
    DIALOG: 'LH_DIALOG',
    CHANGETYPE: 'LH_CHANGETYPE',
    CHANGESTARTTIME: 'LH_CHANGESTARTTIME',
    CHANGEENDTIME: 'LH_CHANGEENDTIME',
};

export const ACTION_LT = {
    SAVEPARAM: 'LT_SAVEPARAM',
    REQUEST: 'LT_REQUEST',
    RECEIVE: 'LT_RECEIVE',
    TASKSTATUS: 'LT_TASKSTATUS',
    CHANGEWORDCOUNT: 'LT_CHANGEWORDCOUNT',
    STARTTEST: 'LT_STARTTEST',
    ENDTEST: 'LT_ENDTEST',
    CHANGECONTENT: 'LT_CHANGECONTENT',
    CORRECTCOUNT: 'LT_CORRECTCOUNT',
    SELECTCOUNT: 'LT_SELECTCOUNT',
    CHANGEFAILUREARRAY: 'LT_CHANGEFAILUREARRAY',
    CHANGESELECTSTATUS: 'LT_CHANGESELECTSTATUS',
    CHANGEFAILEINDEX: 'LT_CHANGEFAILEINDEX',
    CHANGEFAILEINDEXARRAY: 'LT_CHANGEFAILEINDEXARRAY',
    CHANGEFAILETEMPINDEXARRAY: 'LT_CHANGEFAILETEMPINDEXARRAY',
};
export const ACTION_LW = {
    REQUEST: 'LW_REQUEST',
    RECEIVE: 'LW_RECEIVE',
    CURRENTROWS: 'LW_CURRENTROWS',
    CHANGESHOWALLSTATUS: 'LW_CHANGESHOWALLSTATUS',
};
export const ACTION_WC = {
    REQUEST: 'WC_REQUEST',
    RECEIVE: 'WC_RECEIVE',
    AUTOCHANGEWORDSTATUS: 'WC_AUTOCHANGEWORD',
    REVISECHANGEWORDSTATUS: 'WC_REVISECHANGEWORD',
    REVISEINDEXARRAY: 'WC_REVISEINDEXARRAY',
    REVISEINDEX: 'WC_REVISEINDEX',
    AUTOCHANGETIME: 'WC_AUTOCHANGETIME',
    CHANGEAUTOTIMER: 'WC-CHANGEAUTOTIMER',
    TOGGLETIMER: 'WC-TOGGLETIMER',
    CHANGECURRENTINDEX: 'WC_CHANGECURRENTINDEX',
    TOGGLEBACK: 'WC_TOGGLEBACK',
    CHANGEKNOWNSTATUS: 'WC_CHANGEKNOWNSTATUS',
    ORIGINROWS: 'WC_ORIGINROWS',
};

export const REQUEST_CURRENT_TASK = 'REQUEST_CURRENT_TASK';
export const RECEIVE_CURRENT_TASK = 'RECEIVE_CURRENT_TASK';

export const REQUEST_MY_COURSE_LIST = 'REQUEST_MY_COURSE_LIST';
export const RECEIVE_MY_COURSE_LIST = 'RECEIVE_MY_COURSE_LIST';

export const RECIVE_LESSON_TREE = 'RECIVE_LESSON_TREE';
export const RECIVE_LESSON_DETAIL = 'RECIVE_LESSON_DETAIL';
export const RECIVE_TASK_SHARE = 'RECIVE_TASK_SHARE';
