/**
 * Created by joe on 4/19/18.
 */
// export const REQUEST_CONTENT_QUIZ = 'REQUEST_CONTENT_QUIZ';
export const RECEIVE_CONTENT_QUIZ = 'RECEIVE_CONTENT_QUIZ';

// export const REQUEST_STATS_QUIZ_SAVE = 'REQUEST_STATS_QUIZ_SAVE';
// export const RECEIVE_STATS_QUIZ_SAVE = 'RECEIVE_STATS_QUIZ_SAVE';

// export const REQUEST_STATS_QUIZ_UPDATE = 'REQUEST_STATS_QUIZ_UPDATE';
// export const RECEIVE_STATS_QUIZ_UPDATE = 'RECEIVE_STATS_QUIZ_UPDATE';

export const SAVE_QUESTION1_SELECT_VALUE = 'SAVE_QUESTION1_SELECT_VALUE';
export const SAVE_QUESTION3_SELECT_VALUE = 'SAVE_QUESTION3_SELECT_VALUE';
export const SAVE_QUESTION3_TEXT_VALUE = 'SAVE_QUESTION3_TEXT_VALUE';
export const SAVE_QUESTION3_TEXT_SCORE = 'SAVE_QUESTION3_TEXT_SCORE';
export const SAVE_QUESTION4_TEXT_VALUE = 'SAVE_QUESTION4_TEXT_VALUE';
export const SAVE_QUESTION_FEEDBACK = 'SAVE_QUESTION_FEEDBACK';

export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const RESTORE_LOCAL_ANSWERS = 'RESTORE_LOCAL_ANSWERS';
export const RECORD_TIME = 'RECORD_TIME';
export const SHOW_UNCOMPLETED_QUESTION = 'SHOW_UNCOMPLETED_QUESTION';
export const SHOW_ALL_QUESTION = 'SHOW_ALL_QUESTION';
export const UPDATE_ANSWERS = 'UPDATE_ANSWERS';
